<div class="swiper-slide">
							<div class="index_new_text">
								<div class="index_new_text_nei">
									<div class="index_new_title"><span class="index_new_title1">[field:title/]</span><span class="index_new_title2">[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></div>
									
									<div class="index_new_link">了解更多>></div>
									<div class="clear"></div>
								</div>
							</div>
							<div class="index_new_img"><img src="[field:litpic/]"></div>
							<div class="clear"></div>
						</div>