<?php
$z[0]=Array("arcur","",22,36);
$z[1]=Array("title","",56,70);
$z[2]=Array("pubdate","",82,129);
$z[2][4]['function']="MyDate('Y-m-d',@me)";
$z[3]=Array("arcurl","",717,732);
$z[4]=Array("title","",734,748);
$z[5]=Array("litpic","",770,785);
$z[6]=Array("arcur","",1656,1670);
$z[7]=Array("title","",1758,1772);
$z[8]=Array("pubdate","",1785,1832);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("arcur","",2401,2415);
$z[10]=Array("title","",2512,2526);
$z[11]=Array("pubdate","",2540,2587);
$z[11][4]['function']="MyDate('Y-m-d',@me)";

?>