<?php
$z[0]=Array("channelartlist","\r\n			<div class=\"menu_xun\">\r\n				<a class=\"menu_title\">\r\n					<div class=\"menu_xian\">\r\n						<div></div>\r\n					</div>{dede:field name='typename'/}\r\n				</a>\r\n				<ul>\r\n					  {dede:channel type='son' noself='yes'}\r\n					<li>\r\n						<a href=\"[field:typelink/]\"> [field:typename/]</a>\r\n					</li>\r\n					  {/dede:channel}\r\n					\r\n				</ul>\r\n			</div>\r\n\r\n			",358,776);
$z[0][4]['typeid']="top";
$z[0][4]['row']="8";

?>