<?php
$z[0]=Array("include","",898,933);
$z[0][4]['filename']="head.htm";
$z[1]=Array("arclist","\r\n						<div class=\"swiper-slide\">\r\n							<div class=\"index_new_text\">\r\n								<div class=\"index_new_text_nei\">\r\n									<div class=\"index_new_title\"><span class=\"index_new_title1\">[field:title/]</span><span class=\"index_new_title2\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></div>\r\n									\r\n									<div class=\"index_new_link\">了解更多>></div>\r\n									<div class=\"clear\"></div>\r\n								</div>\r\n							</div>\r\n							<div class=\"index_new_img\"><img src=\"[field:litpic/]\"></div>\r\n							<div class=\"clear\"></div>\r\n						</div>\r\n						",1308,1916);
$z[1][4]['flag']="c";
$z[1][4]['limit']="0,5";
$z[2]=Array("arclist","\r\n						<li>\r\n							<a href=\"[field:arcur/]\"  target=\"_blank\"> [field:textlink/]</a> <span> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]	</span>\r\n						</li>\r\n						",2560,2799);
$z[2][4]['flag']="h";
$z[2][4]['typeid']="11";
$z[2][4]['limit']="0,9";
$z[2][4]['col']="1";
$z[3]=Array("arclist","\r\n					<li>\r\n						<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n						<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" style=\"width:400px;height:260px\"></a>\r\n					</li>\r\n					",3290,3523);
$z[3][4]['typeid']="35";
$z[3][4]['limit']="0,2";
$z[4]=Array("arclist","\r\n						<li>\r\n							<a href=\"[field:arcur/]\"  target=\"_blank\"> [field:textlink/]</a> <span>  [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n						</li>\r\n						",4312,4543);
$z[4][4]['typeid']="13";
$z[4][4]['limit']="0,9";
$z[4][4]['col']="1";
$z[5]=Array("arclist","\r\n						<li>\r\n							<a href=\"[field:arcur/]\"  target=\"_blank\"> [field:textlink/]  </a> <span> [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]	</span>\r\n						</li>\r\n						",5047,5288);
$z[5][4]['flag']="h";
$z[5][4]['typeid']="12";
$z[5][4]['limit']="0,9";
$z[5][4]['col']="1";
$z[6]=Array("include","",6440,6477);
$z[6][4]['filename']="footer.htm";

?>