<?php
$z[0]=Array("include","",966,1001);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channel","\r\n					<li>\r\n						<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n					</li>\r\n					",1354,1491);
$z[1][4]['typeid']="2";
$z[1][4]['type']="son";
$z[2]=Array("field","",1558,1580);
$z[2][4]['name']="typename";
$z[3]=Array("list","\r\n					<li>\r\n						<a href=\"\">[field:textlink/]</a>\r\n						<span>2017-12-05</span>\r\n					</li>\r\n					",1609,1763);
$z[3][4]['flag']="h";
$z[3][4]['pagesize']="9";
$z[3][4]['col']="1";
$z[4]=Array("pagelist","",1861,1922);
$z[4][4]['listitem']="info,pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",2218,2255);
$z[5][4]['filename']="footer.htm";

?>