<?php
$z[0]=Array("include","",1238,1273);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",1600,1622);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n					\r\n					<li>\r\n						<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n					</li>\r\n					",1650,1783);
$z[2][4]['type']="son";
$z[3]=Array("field","",1850,1872);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1890,1911);
$z[4][4]['name']="content";
$z[5]=Array("include","",1973,2010);
$z[5][4]['filename']="footer.htm";

?>