<?php
$z[0]=Array("include","",1142,1177);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",1372,1391);
$z[1][4]['name']="title";
$z[2]=Array("field","",1458,1514);
$z[2][4]['name']="pubdate";
$z[2][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[3]=Array("field","",1560,1581);
$z[3][4]['name']="writer";
$z[4]=Array("field","",2601,2619);
$z[4][4]['name']="body";
$z[5]=Array("arclist","\r\n						<li><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n							<a href=\"[field:arcur/]\">[field:textlink/]</a>\r\n						</li>\r\n						",2777,2995);
$z[5][4]['flag']="h";
$z[5][4]['typeid']="11";
$z[5][4]['limit']="0,9";
$z[5][4]['col']="1";
$z[6]=Array("include","",3105,3142);
$z[6][4]['filename']="footer.htm";

?>