<?php
$z[0]=Array("include","",1142,1177);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",1372,1433);
$z[1][4]['name']="typename";
$z[1][4]['function']="GetTypeName（@me）";
$z[2]=Array("field","",1500,1556);
$z[2][4]['name']="pubdate";
$z[2][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[3]=Array("field","",1602,1623);
$z[3][4]['name']="writer";
$z[4]=Array("field","",2643,2664);
$z[4][4]['name']="content";
$z[5]=Array("arclist","\r\n						<li><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span>\r\n							<a href=\"[field:arcur/]\">[field:textlink/]</a>\r\n						</li>\r\n						",2822,3040);
$z[5][4]['flag']="h";
$z[5][4]['typeid']="11";
$z[5][4]['limit']="0,9";
$z[5][4]['col']="1";
$z[6]=Array("include","",3150,3187);
$z[6][4]['filename']="footer.htm";

?>